id: P000685
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:00.557003
source_metadata:
  id: bdr:W1KG17024
  title: ཧོར་འདུལ་གཡུལ་རྒྱལ་ལྷའི་རྔ་སྒྲ།
  author: ''
  volumes:
    8f112ce6f1c942d8af478663ea699469:
      image_group_id: I1KG17061
      title: ''
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
