id: P000685
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17024
  title: ཧོར་འདུལ་གཡུལ་རྒྱལ་ལྷའི་རྔ་སྒྲ།
  author: ''
  volumes:
    8f112ce6f1c942d8af478663ea699469:
      image_group_id: I1KG17061
      title: ''
      volume_number: 1
      total_pages: 208
